language: php

php:
  - '7.0'
  - '7.1'

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install

script: vendor/bin/phpunit

matrix:
  allow_failures:
    - php: 7.1
  fast_finish: true